FROM node:14 as backend
WORKDIR /app
COPY /backend/package*.json ./
RUN npm install
COPY /backend ./
EXPOSE 8080
CMD ["node", "src/index.ts"]

FROM node:14 as frontend
WORKDIR /app/frontend
COPY /frontend/package*.json ./
RUN npm install
COPY /frontend ./
RUN npm run build
EXPOSE 3000
CMD ["npm", "start"]