# version: "3"
# services:
#   backend:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: backend
#     ports:
#       - "8080:8080"
#     restart: always
#   frontend:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: frontend
#     ports:
#       - "3000:3000"
#     restart: always
#     depends_on:
#       - backend
